//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chromathud {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chromathud.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Clears.
        /// </summary>
        internal static string EnableGroupClear {
            get {
                return ResourceManager.GetString("EnableGroupClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endless.
        /// </summary>
        internal static string EndlessMode {
            get {
                return ResourceManager.GetString("EndlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster Scoring.
        /// </summary>
        internal static string FastScoring {
            get {
                return ResourceManager.GetString("FastScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen .
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Play.
        /// </summary>
        internal static string HowToPlay {
            get {
                return ResourceManager.GetString("HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert on Push.
        /// </summary>
        internal static string InvertOnPush {
            get {
                return ResourceManager.GetString("InvertOnPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Numbers.
        /// </summary>
        internal static string LessThan10 {
            get {
                return ResourceManager.GetString("LessThan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Selection.
        /// </summary>
        internal static string MaxSelect {
            get {
                return ResourceManager.GetString("MaxSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string MultiPlay {
            get {
                return ResourceManager.GetString("MultiPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon Blocks.
        /// </summary>
        internal static string NeonBlocks {
            get {
                return ResourceManager.GetString("NeonBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        internal static string PressStart {
            get {
                return ResourceManager.GetString("PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Explosions.
        /// </summary>
        internal static string ShapedExplosions {
            get {
                return ResourceManager.GetString("ShapedExplosions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Speed.
        /// </summary>
        internal static string StartingSpeed {
            get {
                return ResourceManager.GetString("StartingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Hints.
        /// </summary>
        internal static string TargetNotifications {
            get {
                return ResourceManager.GetString("TargetNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Attack.
        /// </summary>
        internal static string TimedMode {
            get {
                return ResourceManager.GetString("TimedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translucent Blocks.
        /// </summary>
        internal static string TranslucentBlocks {
            get {
                return ResourceManager.GetString("TranslucentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This completes the tutorial. The game will now be in Endless mode, but you can play the tutorial again any time you wish. Have fun!.
        /// </summary>
        internal static string TutorialCompleted {
            get {
                return ResourceManager.GetString("TutorialCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a block is deselected, it turns grey. Grey blocks can only be cleared by clearing two or more adjacent blocks at the same time..
        /// </summary>
        internal static string TutorialDeadBlocks {
            get {
                return ResourceManager.GetString("TutorialDeadBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will lose if any blocks hit the top of the field. So don&apos;t let them!.
        /// </summary>
        internal static string TutorialHowToLose {
            get {
                return ResourceManager.GetString("TutorialHowToLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Chromathud. This is a rising block puzzle game where the goal is to select numbered blocks that add up to the target number. Your first target is {0}. Find a {0} block and {1}!.
        /// </summary>
        internal static string TutorialIntro {
            get {
                return ResourceManager.GetString("TutorialIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click it.
        /// </summary>
        internal static string TutorialIntroPC {
            get {
                return ResourceManager.GetString("TutorialIntroPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press {A}.
        /// </summary>
        internal static string TutorialIntroXbox {
            get {
                return ResourceManager.GetString("TutorialIntroXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you gain more points, you will also gain the ability to select more blocks at one time. Your limit is now {0}!.
        /// </summary>
        internal static string TutorialLimitIncreased {
            get {
                return ResourceManager.GetString("TutorialLimitIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not enough blocks remain, you can make them rise faster by pressing {0}. Be careful not to go too far!.
        /// </summary>
        internal static string TutorialPushing {
            get {
                return ResourceManager.GetString("TutorialPushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacebar.
        /// </summary>
        internal static string TutorialPushingPC {
            get {
                return ResourceManager.GetString("TutorialPushingPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {LT}.
        /// </summary>
        internal static string TutorialPushingXbox {
            get {
                return ResourceManager.GetString("TutorialPushingXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on a block to deselect it..
        /// </summary>
        internal static string TutorialSelectLimitPC {
            get {
                return ResourceManager.GetString("TutorialSelectLimitPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you start out you can select a maximum of 3 blocks at the same time. Your current limit can be seen on the right. If you reach this limit, you must deselect some blocks to continue. {0}.
        /// </summary>
        internal static string TutorialSelectLimitReached {
            get {
                return ResourceManager.GetString("TutorialSelectLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can deselect blocks by pressing {B}.
        /// </summary>
        internal static string TutorialSelectLimitXbox {
            get {
                return ResourceManager.GetString("TutorialSelectLimitXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time you reach your target, it changes. The target is now {0}.
        /// </summary>
        internal static string TutorialTargetChanged {
            get {
                return ResourceManager.GetString("TutorialTargetChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string TutorialTest {
            get {
                return ResourceManager.GetString("TutorialTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string TutorialTest1 {
            get {
                return ResourceManager.GetString("TutorialTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string XDifficulty {
            get {
                return ResourceManager.GetString("XDifficulty", resourceCulture);
            }
        }
    }
}
